package com.sample

import java.util.LinkedList;

rule "init"
	when
	then
		insert(new Attribute("rodzaj", "nieznany"));
end

rule "Wykryj rodzaj"
    when
        $rodzaj : Attribute( name == "rodzaj", value == "nieznany" )
    then
        Questionaire questionaire = new Questionaire("Wykryj rodzaj");
        LinkedList<String> answers = questionaire.askUser();
       	
       	retract($rodzaj);
       	for(String answer : answers) {
       		insert(new Attribute("rodzaj", answer));
       	}
end

rule "Określ rasę"
	when
		$rodzaj : Attribute( name == "rodzaj", value == "humanoid" )
		not $potwor : Attribute( name == "rodzaj", value == "potwór" )
	then
		Questionaire questionaire = new Questionaire("Określ rasę");
		LinkedList<String> answers = questionaire.askUser();
       	
       	for(String answer : answers) {
       		insert(new Attribute("rasa", answer));
       	}
end

rule "Określ płeć"
	when
		$humanoid : Attribute( name == "rodzaj", value == "humanoid" )
	then
		Questionaire questionaire = new Questionaire("Określ płeć");
       	LinkedList<String> answers = questionaire.askUser();
       	
       	for(String answer : answers) {
       		insert(new Attribute("płeć", answer));
       	}
end

rule "Określ szczególną cechę hybrydy (mężczyzna)"
	when
		$humanoid : Attribute( name == "rodzaj", value == "humanoid" )
		$potwor : Attribute( name == "rodzaj", value == "potwór" )
		$plec : Attribute( name == "płeć", value == "mężczyzna" )
	then
		Questionaire questionaire = new Questionaire("Określ szczególną cechę hybrydy (mężczyzna)");
       	LinkedList<String> answers = questionaire.askUser();
       	
       	for(String answer : answers) {
       		insert(new Attribute("cecha szczególna", answer));
       	}
end

rule "Określ szczególną cechę hybrydy (kobieta)"
	when
		$humanoid : Attribute( name == "rodzaj", value == "humanoid" )
		$potwor : Attribute( name == "rodzaj", value == "potwór" )
		$plec : Attribute( name == "płeć", value == "kobieta" )
	then
		Questionaire questionaire = new Questionaire("Określ szczególną cechę hybrydy (kobieta)");
       	LinkedList<String> answers = questionaire.askUser();
       	
       	for(String answer : answers) {
       		insert(new Attribute("cecha szczególna", answer));
       	}
end

rule "To wampir"
	when
		$plec : Attribute( name == "płeć", value == "mężczyzna" )
		Attribute( name == "cecha szczególna", value == "Pije krew")
	then
		Questionaire questionaire = new Questionaire("To wampir");
       	questionaire.informUser();
end

rule "To wilkołak"
	when
		$plec : Attribute( name == "płeć", value == "mężczyzna" )
		Attribute( name == "cecha szczególna", value == "Reaguje na pełnię księżyca")
	then
		Questionaire questionaire = new Questionaire("To wilkołak");
       	questionaire.informUser();
end

rule "To sukkub"
	when
		Attribute( name == "cecha szczególna", value == "Wysysa siły witalne")
	then
		Questionaire questionaire = new Questionaire("To sukkub");
       	questionaire.informUser();
end

rule "To wampirzyca"
	when
		Attribute( name == "płeć", value == "kobieta")
		Attribute( name == "cecha szczególna", value == "Pije krew")
	then
		Questionaire questionaire = new Questionaire("To wampirzyca");
       	questionaire.informUser();
end

rule "Określ czy jest mutantem"
	when
		Attribute( name == "rasa", value == "człowiek" )
		Attribute( name == "płeć", value == "mężczyzna" )
		Attribute( name == "profesja", value == "walka" )
	then
		Questionaire questionaire = new Questionaire("Określ czy jest mutantem");
       	LinkedList<String> answers = questionaire.askUser();
       	
       	for(String answer : answers) {
       		insert(new Attribute("mutant", answer));
       	}
end

rule "Określ cechę szczególną wiedźmina"
	when
		Attribute( name == "mutant", value == "Tak" )
	then
		Questionaire questionaire = new Questionaire("Określ cechę szczególną wiedźmina");
       	LinkedList<String> answers = questionaire.askUser();
       	
       	for(String answer : answers) {
       		insert(new Attribute("cecha szczególna", answer));
       	}
end

rule "To Coen"
	when
		Attribute( name == "mutant", value == "Tak" )
		Attribute( name == "cecha szczególna", value == "Żółte oczy" )
	then
		Questionaire questionaire = new Questionaire("To Coen");
       	questionaire.informUser();
end

rule "To Eskel"
	when
		Attribute( name == "mutant", value == "Tak" )
		Attribute( name == "cecha szczególna", value == "Duża blizna na twarzy" )
	then
		Questionaire questionaire = new Questionaire("To Eskel");
       	questionaire.informUser();
end

rule "To Geralt"
	when
		Attribute( name == "mutant", value == "Tak" )
		Attribute( name == "cecha szczególna", value == "Białe włosy" )
	then
		Questionaire questionaire = new Questionaire("To Geralt");
       	questionaire.informUser();
end

rule "Określ profesje"
	when
		$humanoid : Attribute( name == "rodzaj", value == "humanoid" )
		not $potwór : Attribute( name == "rodzaj", value == "potwór" )
	then
		Questionaire questionaire = new Questionaire("Określ profesje");
       	LinkedList<String> answers = questionaire.askUser();
       	
       	for(String answer : answers) {
       		insert(new Attribute("profesja", answer));
       	}
end

rule "Określ którymi państwami włada (mężczyzna)"
	when
		$profesja : Attribute( name == "profesja", value == "sprawowanie władzy" )
		$rasa : Attribute( name == "rasa", value == "człowiek" )
		$plec : Attribute( name == "płeć", value == "mężczyzna" )
		
	then
		Questionaire questionaire = new Questionaire("Określ którymi państwami włada (mężczyzna)");
       	LinkedList<String> answers = questionaire.askUser();
       	
       	for(String answer : answers) {
       		insert(new Attribute("zarządzane państwo", answer));
       	}
end

rule "Określ którymi państwami włada (kobieta)"
	when
		$profesja : Attribute( name == "profesja", value == "sprawowanie władzy" )
		$rasa : Attribute( name == "rasa", value != "krasnolud" )
		$plec : Attribute( name == "płeć", value == "kobieta" )

	then
		Questionaire questionaire = new Questionaire("Określ którymi państwami włada (kobieta)");
       	LinkedList<String> answers = questionaire.askUser();
       	
       	for(String answer : answers) {
       		insert(new Attribute("zarządzane państwo", answer));
       	}
end

rule "To Meve"
	when
		$panstwo : Attribute( name == "zarządzane państwo", value == "Lyria i Rivia" )
		$rasa : Attribute( name == "rasa", value == "człowiek" )
	then
		Questionaire questionaire = new Questionaire("To Meve");
       	questionaire.informUser();
end

rule "To Calanthe"
	when
		$panstwo : Attribute( name == "zarządzane państwo", value == "Cintra" )
		$rasa : Attribute( name == "rasa", value == "człowiek" )
	then
		Questionaire questionaire = new Questionaire("To Calanthe");
       	questionaire.informUser();
end

rule "To Francesca Findabair"
	when
		$panstwo : Attribute( name == "zarządzane państwo", value == "Dol Blathanna" )
		$rasa : Attribute( name == "rasa", value == "elf" )
	then
		Questionaire questionaire = new Questionaire("To Francesca Findabair");
       	questionaire.informUser();
end

rule "To Esterad Thyssen"
	when
		$panstwo : Attribute( name == "zarządzane państwo", value == "Kovir" )
	then
		Questionaire questionaire = new Questionaire("To Esterad Thyssen");
       	questionaire.informUser();
end

rule "To Emhyr"
	when
		$panstwo : Attribute( name == "zarządzane państwo", value == "Nilfgaard" )
	then
		Questionaire questionaire = new Questionaire("To Emhyr");
       	questionaire.informUser();
end

rule "To Henselt"
	when
		$panstwo : Attribute( name == "zarządzane państwo", value == "Kaedwen" )
	then
		Questionaire questionaire = new Questionaire("To Henselt");
       	questionaire.informUser();
end

rule "To Demawend"
	when
		$panstwo : Attribute( name == "zarządzane państwo", value == "Aedirn" )
	then
		Questionaire questionaire = new Questionaire("To Demawend");
       	questionaire.informUser();
end

rule "To Foltest"
	when
		$panstwo : Attribute( name == "zarządzane państwo", value == "Temeria" )
	then
		Questionaire questionaire = new Questionaire("To Foltest");
       	questionaire.informUser();
end

rule "To Radovid"
	when
		$panstwo : Attribute( name == "zarządzane państwo", value == "Redania" )
	then
		Questionaire questionaire = new Questionaire("To Radovid");
       	questionaire.informUser();
end

rule "To bard Jaskier"
	when
		Attribute( name == "profesja", value == "kreatywność" )
		Attribute( name == "płeć", value == "mężczyzna" )
		Attribute( name == "rasa", value == "człowiek" )
	then
		Questionaire questionaire = new Questionaire("To bard Jaskier");
       	questionaire.informUser();
end

rule "Określ czy to zaręczony krasnolud"
	when
		Attribute( name == "rasa", value == "krasnolud" )
	then
		Questionaire questionaire = new Questionaire("Określ czy to zaręczony krasnolud");
       	LinkedList<String> answers = questionaire.askUser();
       	
       	for(String answer : answers) {
       		insert(new Attribute("zaręczyny", answer));
       	}
end

rule "To Zoltan Chivay"
	when
		Attribute( name == "profesja", value == "walka" )
		Attribute( name == "płeć", value == "mężczyzna" )
		Attribute( name == "rasa", value == "krasnolud" )
		Attribute( name == "zaręczyny", value == "Tak" )
	then
		Questionaire questionaire = new Questionaire("To Zoltan Chivay");
       	questionaire.informUser();
end

rule "To Yarpen"
	when
		Attribute( name == "profesja", value == "walka" )
		Attribute( name == "płeć", value == "mężczyzna" )
		Attribute( name == "rasa", value == "krasnolud" )
		Attribute( name == "zaręczyny", value == "Nie" )
	then
		Questionaire questionaire = new Questionaire("To Yarpen");
       	questionaire.informUser();
end

rule "Określ czy romansowała z Geraltem"
	when 
		$plec : Attribute( name == "płeć", value == "kobieta" )
		$race : Attribute( name == "rasa", value == "człowiek" )
	then
		Questionaire questionaire = new Questionaire("Określ czy romansowała z Geraltem");
        LinkedList<String> answers = questionaire.askUser();
       	
       	for(String answer : answers) {											 
       		insert(new Attribute("romans", answer));
       	}
end

rule "Określ czy doradza jakiemuś królowi"
	when 
		$race : Attribute( name == "rasa", value == "człowiek" )
		$profesja : Attribute( name == "profesja", value == "magia" )
	then
		Questionaire questionaire = new Questionaire("Określ czy doradza jakiemuś królowi");
        LinkedList<String> answers = questionaire.askUser();
       	
       	for(String answer : answers) {											 
       		insert(new Attribute("doradza", answer));
       	}
end

rule "To Filippa Eilhart"
	when 
		Attribute( name == "doradza", value == "Radovid" ) 
		Attribute( name == "płeć", value == "kobieta" )
	then
		Questionaire questionaire = new Questionaire("To Filippa Eilhart");
       	questionaire.informUser();
end

rule "To Sabrina Glevissig"
	when 
		Attribute( name == "doradza", value == "Henselt" ) 
		Attribute( name == "płeć", value == "kobieta" )
	then
		Questionaire questionaire = new Questionaire("To Sabrina Glevissig");
       	questionaire.informUser();
end

rule "It's Fringilla Vigo"
	when 
		$serves : Attribute( (name == "served_in" && value == "Nilfgard") || (name == "hair" && value == "short")  )
		$gender : Attribute( name == "gender", value == "female" )
		$race : Attribute( name == "race", value == "human" )
		$romanced : Attribute( name == "romanced_geralt", value == "yes" )
	then
		System.out.println("It's Sabrina Glevisig");
end

rule "To Triss"
	when 
		Attribute( name == "doradza", value == "Foltest" ) 
		Attribute( name == "płeć", value == "kobieta" )
		Attribute( name == "romans", value == "tak" )
	then
		Questionaire questionaire = new Questionaire("To Triss");
       	questionaire.informUser();
end

rule "To Yennefer"
	when 
		not Attribute( name == "doradza" ) 
		Attribute( name == "płeć", value == "kobieta" )
		Attribute( name == "romans", value == "tak" )
		Attribute( name == "profesja", value == "magia" )
	then
		Questionaire questionaire = new Questionaire("To Yennefer");
       	questionaire.informUser();
end

rule "Determine Geralt's familiar sorceress hair color"
	when 
		$romanced : Attribute( name == "romanced_geralt", value == "yes" )
		$served_in : Attribute( name == "served_in", value == "dont know" )
	then
		Questionaire questionaire = new Questionaire("What is her hair like?");
        LinkedList<String> answers = questionaire.askUser();
       	
       	for(String answer : answers) {											 
       		insert(new Attribute("hair", answer));
       	}
end

rule "Determine woman's hair color"
	when 
		$gender : Attribute( name == "gender", value == "female" )
		$race : Attribute( name == "race", value == "human" )
	then
		Questionaire questionaire = new Questionaire("What is her hair like?");
        LinkedList<String> answers = questionaire.askUser();
       	
       	for(String answer : answers) {											 
       		insert(new Attribute("hair", answer));
       	}
end

rule "It's Ciri"
	when
		$gender : Attribute( name == "gender", value == "female" )
		$race : Attribute( name == "race", value == "human" )
		$romanced : Attribute( name == "romanced_geralt", value == "no" )
		$profession : Attribute( (name == "profession") && (value == "combat" || value == "magic") )
		$hair : Attribute( name == "hair", value == "ashen" )
	then
		System.out.println("It's Ciri of Cintra");
end