package com.sample

import java.util.LinkedList;

rule "init"
	when
	then
		insert(new Attribute("kind", "unknown"));
end

rule "Wykryj rodzaj"
    when
        $kind : Attribute( name == "kind", value == "unknown" )
    then
        Questionaire questionaire = new Questionaire("Wykryj rodzaj");
        LinkedList<String> answers = questionaire.askUser();
       	
       	for(String answer : answers) {
       		insert(new Attribute("kind", answer));
       	}
end

rule "Determine non-magical race"
	when
		$profession : Attribute( name == "profession", value != "magic" )
	then
		Questionaire questionaire = new Questionaire("What is a race?");
		LinkedList<String> answers = questionaire.askUser();
       	
       	for(String answer : answers) {
       		insert(new Attribute("race", answer));
       	}
end

rule "Determine magical race"
	when
		$profession : Attribute( name == "profession", value == "magic" )
	then
		Questionaire questionaire = new Questionaire("What is a race?");
        LinkedList<String> answers = questionaire.askUser();
       	
       	for(String answer : answers) {											 
       		insert(new Attribute("race", answer));
       	}
end

rule "Determine gender"
	when
		$kind : Attribute( name == "kind", value == "humanoid" )
	then
		Questionaire questionaire = new Questionaire("What is a gender?");
       	LinkedList<String> answers = questionaire.askUser();
       	
       	for(String answer : answers) {
       		insert(new Attribute("gender", answer));
       	}
end

rule "Determine hair color for witcher" 
	when
		$kind : Attribute( name == "kind", value == "humanoid" )
		$mutant : Attribute( name == "mutant", value == "yes" )
	then
		Questionaire questionaire = new Questionaire("What is character's hair color?");
       	LinkedList<String> answers = questionaire.askUser();
       	
       	for(String answer : answers) {
       		insert(new Attribute("hair", answer));
       	}
end

rule "Determine witchers specific feature"
	when
		$mutant : Attribute( name == "mutant", value == "yes" )
		$hair : Attribute( name == "hair", value == "dark" )
	then
		Questionaire questionaire = new Questionaire("What is witcher's specific feature?");
       	LinkedList<String> answers = questionaire.askUser();
       	
       	for(String answer : answers) {
       		insert(new Attribute("specific_feature", answer));
       	}
end

rule "It's Lambert"
	when
		$mutant : Attribute( name == "mutant", value == "yes" )
		$feature : Attribute( name == "specific_feature", value == "irony" )
	then
		System.out.println("It's Lambert");
end

rule "It's Coen"
	when
		$mutant : Attribute( name == "mutant", value == "yes" )
		$feature : Attribute( name == "specific_feature", value == "yellow eyes" )
	then
		System.out.println("It's Coen");
end

rule "It's Eskel"
	when
		$mutant : Attribute( name == "mutant", value == "yes" )
		$feature : Attribute( name == "specific_feature", value == "big scar on face" )
	then
		System.out.println("It's Eskel");
end

rule "Determine what is character doing best"
	when
		$kind : Attribute( name == "kind", value == "humanoid" )
	then
		Questionaire questionaire = new Questionaire("What is character's profession?");
       	LinkedList<String> answers = questionaire.askUser();
       	
       	for(String answer : answers) {
       		insert(new Attribute("profession", answer));
       	}
end

rule "Determine if rules"
	when
		$profession : Attribute( name == "profession", value == "power")
		$race : Attribute( name == "race", value == "human" )
	then
		Questionaire questionaire = new Questionaire("Has this character ever ruled any kingdom?");
       	LinkedList<String> answers = questionaire.askUser();
       	
       	for(String answer : answers) {
       		insert(new Attribute("ruled", answer));
       	}
end

rule "Determine country ruled by woman"
	when
		$ruled : Attribute( name == "ruled", value == "yes" )
		$gender : Attribute( name == "gender", value == "female" )
	then
		Questionaire questionaire = new Questionaire("Which has she ruled?");
       	LinkedList<String> answers = questionaire.askUser();
       	
       	for(String answer : answers) {
       		insert(new Attribute("country_ruled", answer));
       	}
end

rule "Determine country ruled by man"
	when
		$ruled : Attribute( name == "ruled", value == "yes" )
		$gender : Attribute( name == "gender", value == "male" )
	then
		Questionaire questionaire = new Questionaire("Which has he ruled?");
       	LinkedList<String> answers = questionaire.askUser();
       	
       	for(String answer : answers) {
       		insert(new Attribute("country_ruled", answer));
       	}
end	

rule "It's Meve"
	when
		$country_ruled : Attribute( name == "country_ruled", value == "Lyria and Rivia" )
	then
		System.out.println("It's Quen Meve");
end

rule "It's Calanthe"
	when
		$country_ruled : Attribute( name == "country_ruled", value == "Cintra" )
	then
		System.out.println("It's Quen Calanthe");
end

rule "It's Esterad Thyssen"
	when
		$country_ruled : Attribute( name == "country_ruled", value == "Kovir" )
	then
		System.out.println("It's Esterad Thyssen");
end

rule "It's Emhyr"
	when
		$country_ruled : Attribute( name == "country_ruled", value == "Nilfgard" )
	then
		System.out.println("It's Emhyr Var Emreis");
end

rule "It's Henselt"
	when
		$country_ruled : Attribute( name == "country_ruled", value == "Kaedwen" )
	then
		System.out.println("It's king Henselt");
end

rule "It's Demawend"
	when
		$country_ruled : Attribute( name == "country_ruled", value == "Aedirn" )
	then
		System.out.println("It's king Demawend");
end

rule "It's Foltest"
	when
		$country_ruled : Attribute( name == "country_ruled", value == "Temeria" )
	then
		System.out.println("It's king Foltest");
end

rule "It's Radovid"
	when
		$country_ruled : Attribute( name == "country_ruled", value == "Redania" )
	then
		System.out.println("It's king Radovid");
end

rule "Determine if it's witcher"
	when
		$race : Attribute( name == "race", value == "human" )
		$profession : Attribute( name == "profession", value == "combat" )
		$gender : Attribute( name == "gender", value == "male" )
	then
		Questionaire questionaire = new Questionaire("Is he a witcher?");
        LinkedList<String> answers = questionaire.askUser();
       	
       	for(String answer : answers) {											 
       		insert(new Attribute("mutant", answer));
       	}
end

rule "It's Geralt"
	when
		$mutant : Attribute( name == "mutant", value == "yes" )
		$hair : Attribute( name == "hair", value == "white" )
	then
		System.out.println("It's Geralt of Rivia");
end

rule "It's Vesemir"
	when 
		$mutant : Attribute( name == "mutant", value == "yes" )
		$hair : Attribute( name == "hair", value == "gray" )
	then
		System.out.println("It's Vesemir");
end

rule "It's bard Jaskier"
	when
		$profession : Attribute( name == "profession", value == "singing" )
		$gender : Attribute( name == "gender", value == "male" )
		$race : Attribute( name == "race", value == "human" )
	then
		System.out.println("It's bard Jaskier");
end

rule "Determine if it's engaged dwarf"
	when
		$race : Attribute( name == "race", value == "dwarf" )
	then
		Questionaire questionaire = new Questionaire("Is your character engaged?");
        LinkedList<String> answers = questionaire.askUser();
       	
       	for(String answer : answers) {											 
       		insert(new Attribute("engaged", answer));
       	}
end

rule "It's Zoltan Chivay"
	when
		$profession : Attribute( name == "profession", value == "combat" )
		$gender : Attribute( name == "gender", value == "male" )
		$race : Attribute( name == "race", value == "dwarf" )
		$engaged : Attribute( name == "engaged", value == "yes" )
	then
		System.out.println("It's Zoltan Chivay");
end

rule "It's Yarpen"
	when
		$profession : Attribute( name == "profession", value == "combat" )
		$gender : Attribute( name == "gender", value == "male" )
		$race : Attribute( name == "race", value == "dwarf" )
		$engaged : Attribute( name == "engaged", value == "no" )
	then
		System.out.println("It's Yarpen Zigrin");
end

rule "It's Eudora Breckenrigs"
	when
		$gender : Attribute( name == "gender", value == "female" )
		$race : Attribute( name == "race", value == "dwarf" )
		$engaged : Attribute( name == "engaged", value == "yes" )
		$profession : Attribute( name == "profession", value == "unknown" )
	then
		System.out.println("It's Eudora Breckenrigs");
end


rule "Determine romanced with Geralt"
	when 
		$gender : Attribute( name == "gender", value == "female" )
		$race : Attribute( name == "race", value == "human" )
	then
		Questionaire questionaire = new Questionaire("Romanced with Geralt of Rivia?");
        LinkedList<String> answers = questionaire.askUser();
       	
       	for(String answer : answers) {											 
       		insert(new Attribute("romanced_geralt", answer));
       	}
end

rule "It's Francesca Findabair"
	when 
		$race : Attribute( name == "race", value == "elf" )
		$profession : Attribute( name == "profession", value == "magic" )
	then
		System.out.println("It's Francesca Findabair");
end

rule "Determine if sorceress served somewhere"
	when 
		$profession : Attribute( name == "profession", value == "magic" )
		$race : Attribute( name == "race", value == "human" )
	then
		Questionaire questionaire = new Questionaire("Served in one of those kingdoms?");
        LinkedList<String> answers = questionaire.askUser();
       	
       	for(String answer : answers) {											 
       		insert(new Attribute("served_in", answer));
       	}
end

rule "It's Filippa Eihlhart"
	when 
		$serves : Attribute( name == "served_in", value == "Redania" )
		$gender : Attribute( name == "gender", value == "female" )
		$race : Attribute( name == "race", value == "human" )
		$romanced : Attribute( name == "romanced_geralt", value == "no" )
	then
		System.out.println("It's Filippa Eihlhart");
end

rule "It's Sabrina Glevisig"
	when 
		$serves : Attribute( name == "served_in", value == "Kaedwen" )
		$gender : Attribute( name == "gender", value == "female" )
		$race : Attribute( name == "race", value == "human" )
		$romanced : Attribute( name == "romanced_geralt", value == "no" )
	then
		System.out.println("It's Sabrina Glevisig");
end

rule "It's Fringilla Vigo"
	when 
		$serves : Attribute( (name == "served_in" && value == "Nilfgard") || (name == "hair" && value == "short")  )
		$gender : Attribute( name == "gender", value == "female" )
		$race : Attribute( name == "race", value == "human" )
		$romanced : Attribute( name == "romanced_geralt", value == "yes" )
	then
		System.out.println("It's Sabrina Glevisig");
end

rule "It's Triss Merigold"
	when 
		$serves : Attribute( (name == "served_in" && value == "Temeria") || (name == "hair" && value == "red")  )
		$gender : Attribute( name == "gender", value == "female" )
		$race : Attribute( name == "race", value == "human" )
		$romanced : Attribute( name == "romanced_geralt", value == "yes" )
	then
		System.out.println("It's Triss Merigold");
end

rule "It's Yennefer"
	when 
		$serves : Attribute( (name == "served_in" && value == "no") || (name == "hair" && value == "black") )
		$gender : Attribute( name == "gender", value == "female" )
		$race : Attribute( name == "race", value == "human" )
		$romanced : Attribute( name == "romanced_geralt", value == "yes" )
	then
		System.out.println("It's Yennefer");
end

rule "Determine Geralt's familiar sorceress hair color"
	when 
		$romanced : Attribute( name == "romanced_geralt", value == "yes" )
		$served_in : Attribute( name == "served_in", value == "dont know" )
	then
		Questionaire questionaire = new Questionaire("What is her hair like?");
        LinkedList<String> answers = questionaire.askUser();
       	
       	for(String answer : answers) {											 
       		insert(new Attribute("hair", answer));
       	}
end

rule "Determine woman's hair color"
	when 
		$gender : Attribute( name == "gender", value == "female" )
		$race : Attribute( name == "race", value == "human" )
	then
		Questionaire questionaire = new Questionaire("What is her hair like?");
        LinkedList<String> answers = questionaire.askUser();
       	
       	for(String answer : answers) {											 
       		insert(new Attribute("hair", answer));
       	}
end

rule "It's Ciri"
	when
		$gender : Attribute( name == "gender", value == "female" )
		$race : Attribute( name == "race", value == "human" )
		$romanced : Attribute( name == "romanced_geralt", value == "no" )
		$profession : Attribute( (name == "profession") && (value == "combat" || value == "magic") )
		$hair : Attribute( name == "hair", value == "ashen" )
	then
		System.out.println("It's Ciri of Cintra");
end