package com.sample

import java.util.LinkedList;

rule "init"
	when
	then
		insert(new Attribute("rodzaj", "nieznany"));
		insert(new Attribute("imię", "nieznane"));
end

rule "Wykryj rodzaj"
    when
        $rodzaj : Attribute( name == "rodzaj", value == "nieznany" )
    then
        Questionaire questionaire = new Questionaire("Wykryj rodzaj");
        LinkedList<String> answers = questionaire.askUser();
       	
       	retract($rodzaj);
       	for(String answer : answers) {
       		insert(new Attribute("rodzaj", answer));
       	}
end

rule "Określ rasę"
	when
		$rodzaj : Attribute( name == "rodzaj", value == "humanoid" )
	then
		Questionaire questionaire = new Questionaire("Określ rasę");
		LinkedList<String> answers = questionaire.askUser();
       	
       	for(String answer : answers) {
       		insert(new Attribute("rasa", answer));
       	}
end

rule "Określ płeć"
	when
		$kind : Attribute( name == "rodzaj", value == "humanoid" )
	then
		Questionaire questionaire = new Questionaire("Określ płeć");
       	LinkedList<String> answers = questionaire.askUser();
       	
       	for(String answer : answers) {
       		insert(new Attribute("płeć", answer));
       	}
end

rule "Określ kolor włosów wiedźmina" 
	when
		$kind : Attribute( name == "rodzaj", value == "humanoid" )
		$mutant : Attribute( name == "mutant", value == "yes" )
	then
		Questionaire questionaire = new Questionaire("What is character's hair color?");
       	LinkedList<String> answers = questionaire.askUser();
       	
       	for(String answer : answers) {
       		insert(new Attribute("hair", answer));
       	}
end

rule "Determine witchers specific feature"
	when
		$mutant : Attribute( name == "mutant", value == "yes" )
		$hair : Attribute( name == "hair", value == "dark" )
	then
		Questionaire questionaire = new Questionaire("What is witcher's specific feature?");
       	LinkedList<String> answers = questionaire.askUser();
       	
       	for(String answer : answers) {
       		insert(new Attribute("specific_feature", answer));
       	}
end

rule "It's Lambert"
	when
		$mutant : Attribute( name == "mutant", value == "yes" )
		$feature : Attribute( name == "specific_feature", value == "irony" )
	then
		System.out.println("It's Lambert");
end

rule "It's Coen"
	when
		$mutant : Attribute( name == "mutant", value == "yes" )
		$feature : Attribute( name == "specific_feature", value == "yellow eyes" )
	then
		System.out.println("It's Coen");
end

rule "It's Eskel"
	when
		$mutant : Attribute( name == "mutant", value == "yes" )
		$feature : Attribute( name == "specific_feature", value == "big scar on face" )
	then
		System.out.println("It's Eskel");
end

rule "Określ profesje"
	when
		$kind : Attribute( name == "rodzaj", value == "humanoid" )
	then
		Questionaire questionaire = new Questionaire("Określ profesje");
       	LinkedList<String> answers = questionaire.askUser();
       	
       	for(String answer : answers) {
       		insert(new Attribute("profesja", answer));
       	}
end

rule "Określ którymi państwami włada (mężczyzna)"
	when
		$profesja : Attribute( name == "profesja", value == "sprawowanie władzy" )
		$rasa : Attribute( name == "rasa", value == "człowiek" )
		$plec : Attribute( name == "płeć", value == "mężczyzna" )
		
	then
		Questionaire questionaire = new Questionaire("Określ którymi państwami włada (mężczyzna)");
       	LinkedList<String> answers = questionaire.askUser();
       	
       	for(String answer : answers) {
       		insert(new Attribute("zarządzane państwo", answer));
       	}
end

rule "Określ którymi państwami włada (kobieta)"
	when
		$profesja : Attribute( name == "profesja", value == "sprawowanie władzy" )
		$rasa : Attribute( name == "rasa", value != "krasnolud" )
		$plec : Attribute( name == "płeć", value == "kobieta" )

	then
		Questionaire questionaire = new Questionaire("Określ którymi państwami włada (kobieta)");
       	LinkedList<String> answers = questionaire.askUser();
       	
       	for(String answer : answers) {
       		insert(new Attribute("zarządzane państwo", answer));
       	}
end

rule "To Meve"
	when
		$imie : Attribute( name == "imię", value == "nieznane" )
		$panstwo : Attribute( name == "zarządzane państwo", value == "Lyria i Rivia" )
		$rasa : Attribute( name == "rasa", value == "człowiek" )
	then
		Questionaire questionaire = new Questionaire("To Meve");
       	questionaire.informUser();
       	
       	retract($imie);
       	insert(new Attribute("imię", "Meve"));
end

rule "To Calanthe"
	when
		$imie : Attribute( name == "imię", value == "nieznane" )
		$panstwo : Attribute( name == "zarządzane państwo", value == "Cintra" )
		$rasa : Attribute( name == "rasa", value == "człowiek" )
	then
		Questionaire questionaire = new Questionaire("To Calanthe");
       	questionaire.informUser();
       	
       	retract($imie);
       	insert(new Attribute("imię", "Calanthe"));
end

rule "To Francesca Findabair"
	when
		$imie : Attribute( name == "imię", value == "nieznane" )
		$panstwo : Attribute( name == "zarządzane państwo", value == "Dol Blathanna" )
		$rasa : Attribute( name == "rasa", value == "elf" )
	then
		Questionaire questionaire = new Questionaire("To Francesca Findabair");
       	questionaire.informUser();
       	
       	retract($imie);
       	insert(new Attribute("imię", "Francesca Findabair"));
end

rule "It's Esterad Thyssen"
	when
		$country_ruled : Attribute( name == "country_ruled", value == "Kovir" )
	then
		System.out.println("It's Esterad Thyssen");
end

rule "It's Emhyr"
	when
		$country_ruled : Attribute( name == "country_ruled", value == "Nilfgard" )
	then
		System.out.println("It's Emhyr Var Emreis");
end

rule "It's Henselt"
	when
		$country_ruled : Attribute( name == "country_ruled", value == "Kaedwen" )
	then
		System.out.println("It's king Henselt");
end

rule "It's Demawend"
	when
		$country_ruled : Attribute( name == "country_ruled", value == "Aedirn" )
	then
		System.out.println("It's king Demawend");
end

rule "It's Foltest"
	when
		$country_ruled : Attribute( name == "country_ruled", value == "Temeria" )
	then
		System.out.println("It's king Foltest");
end

rule "It's Radovid"
	when
		$country_ruled : Attribute( name == "country_ruled", value == "Redania" )
	then
		System.out.println("It's king Radovid");
end

rule "Determine if it's witcher"
	when
		$race : Attribute( name == "race", value == "human" )
		$profession : Attribute( name == "profession", value == "combat" )
		$gender : Attribute( name == "gender", value == "male" )
	then
		Questionaire questionaire = new Questionaire("Is he a witcher?");
        LinkedList<String> answers = questionaire.askUser();
       	
       	for(String answer : answers) {											 
       		insert(new Attribute("mutant", answer));
       	}
end

rule "It's Geralt"
	when
		$mutant : Attribute( name == "mutant", value == "yes" )
		$hair : Attribute( name == "hair", value == "white" )
	then
		System.out.println("It's Geralt of Rivia");
end

rule "It's Vesemir"
	when 
		$mutant : Attribute( name == "mutant", value == "yes" )
		$hair : Attribute( name == "hair", value == "gray" )
	then
		System.out.println("It's Vesemir");
end

rule "It's bard Jaskier"
	when
		$profession : Attribute( name == "profession", value == "singing" )
		$gender : Attribute( name == "gender", value == "male" )
		$race : Attribute( name == "race", value == "human" )
	then
		System.out.println("It's bard Jaskier");
end

rule "Determine if it's engaged dwarf"
	when
		$race : Attribute( name == "race", value == "dwarf" )
	then
		Questionaire questionaire = new Questionaire("Is your character engaged?");
        LinkedList<String> answers = questionaire.askUser();
       	
       	for(String answer : answers) {											 
       		insert(new Attribute("engaged", answer));
       	}
end

rule "It's Zoltan Chivay"
	when
		$profession : Attribute( name == "profession", value == "combat" )
		$gender : Attribute( name == "gender", value == "male" )
		$race : Attribute( name == "race", value == "dwarf" )
		$engaged : Attribute( name == "engaged", value == "yes" )
	then
		System.out.println("It's Zoltan Chivay");
end

rule "It's Yarpen"
	when
		$profession : Attribute( name == "profession", value == "combat" )
		$gender : Attribute( name == "gender", value == "male" )
		$race : Attribute( name == "race", value == "dwarf" )
		$engaged : Attribute( name == "engaged", value == "no" )
	then
		System.out.println("It's Yarpen Zigrin");
end

rule "It's Eudora Breckenrigs"
	when
		$gender : Attribute( name == "gender", value == "female" )
		$race : Attribute( name == "race", value == "dwarf" )
		$engaged : Attribute( name == "engaged", value == "yes" )
		$profession : Attribute( name == "profession", value == "unknown" )
	then
		System.out.println("It's Eudora Breckenrigs");
end


rule "Determine romanced with Geralt"
	when 
		$gender : Attribute( name == "gender", value == "female" )
		$race : Attribute( name == "race", value == "human" )
	then
		Questionaire questionaire = new Questionaire("Romanced with Geralt of Rivia?");
        LinkedList<String> answers = questionaire.askUser();
       	
       	for(String answer : answers) {											 
       		insert(new Attribute("romanced_geralt", answer));
       	}
end

rule "It's Francesca Findabair"
	when 
		$race : Attribute( name == "race", value == "elf" )
		$profession : Attribute( name == "profession", value == "magic" )
	then
		System.out.println("It's Francesca Findabair");
end

rule "Determine if sorceress served somewhere"
	when 
		$profession : Attribute( name == "profession", value == "magic" )
		$race : Attribute( name == "race", value == "human" )
	then
		Questionaire questionaire = new Questionaire("Served in one of those kingdoms?");
        LinkedList<String> answers = questionaire.askUser();
       	
       	for(String answer : answers) {											 
       		insert(new Attribute("served_in", answer));
       	}
end

rule "It's Filippa Eihlhart"
	when 
		$serves : Attribute( name == "served_in", value == "Redania" )
		$gender : Attribute( name == "gender", value == "female" )
		$race : Attribute( name == "race", value == "human" )
		$romanced : Attribute( name == "romanced_geralt", value == "no" )
	then
		System.out.println("It's Filippa Eihlhart");
end

rule "It's Sabrina Glevisig"
	when 
		$serves : Attribute( name == "served_in", value == "Kaedwen" )
		$gender : Attribute( name == "gender", value == "female" )
		$race : Attribute( name == "race", value == "human" )
		$romanced : Attribute( name == "romanced_geralt", value == "no" )
	then
		System.out.println("It's Sabrina Glevisig");
end

rule "It's Fringilla Vigo"
	when 
		$serves : Attribute( (name == "served_in" && value == "Nilfgard") || (name == "hair" && value == "short")  )
		$gender : Attribute( name == "gender", value == "female" )
		$race : Attribute( name == "race", value == "human" )
		$romanced : Attribute( name == "romanced_geralt", value == "yes" )
	then
		System.out.println("It's Sabrina Glevisig");
end

rule "It's Triss Merigold"
	when 
		$serves : Attribute( (name == "served_in" && value == "Temeria") || (name == "hair" && value == "red")  )
		$gender : Attribute( name == "gender", value == "female" )
		$race : Attribute( name == "race", value == "human" )
		$romanced : Attribute( name == "romanced_geralt", value == "yes" )
	then
		System.out.println("It's Triss Merigold");
end

rule "It's Yennefer"
	when 
		$serves : Attribute( (name == "served_in" && value == "no") || (name == "hair" && value == "black") )
		$gender : Attribute( name == "gender", value == "female" )
		$race : Attribute( name == "race", value == "human" )
		$romanced : Attribute( name == "romanced_geralt", value == "yes" )
	then
		System.out.println("It's Yennefer");
end

rule "Determine Geralt's familiar sorceress hair color"
	when 
		$romanced : Attribute( name == "romanced_geralt", value == "yes" )
		$served_in : Attribute( name == "served_in", value == "dont know" )
	then
		Questionaire questionaire = new Questionaire("What is her hair like?");
        LinkedList<String> answers = questionaire.askUser();
       	
       	for(String answer : answers) {											 
       		insert(new Attribute("hair", answer));
       	}
end

rule "Determine woman's hair color"
	when 
		$gender : Attribute( name == "gender", value == "female" )
		$race : Attribute( name == "race", value == "human" )
	then
		Questionaire questionaire = new Questionaire("What is her hair like?");
        LinkedList<String> answers = questionaire.askUser();
       	
       	for(String answer : answers) {											 
       		insert(new Attribute("hair", answer));
       	}
end

rule "It's Ciri"
	when
		$gender : Attribute( name == "gender", value == "female" )
		$race : Attribute( name == "race", value == "human" )
		$romanced : Attribute( name == "romanced_geralt", value == "no" )
		$profession : Attribute( (name == "profession") && (value == "combat" || value == "magic") )
		$hair : Attribute( name == "hair", value == "ashen" )
	then
		System.out.println("It's Ciri of Cintra");
end